#!/bin/bash

export SW_ENABLE=${SW_ENABLE:-"false"}

if is_true "$SW_ENABLE"; then
    SW_AGENT=$(readlink -f /opt/skywalking/skywalking-agent.jar)
    export SW_OPTS=${SW_OPTS:-"-javaagent:${SW_AGENT}"}

    if [ $SW_AGENT_NAMESPACE ]; then
        SW_OPTS=$SW_OPTS "-DSW_AGENT_NAMESPACE=${SW_AGENT_NAMESPACE}"
    fi

    SW_AGENT_NAME=${SW_AGENT_NAME:-"app"}
    SW_OPTS=$SW_OPTS "-DSW_AGENT_NAME=${SW_AGENT_NAME}"

    if [ $SW_AGENT_SAMPLE ]; then
        SW_OPTS=$SW_OPTS "-DSW_AGENT_SAMPLE=${SW_AGENT_SAMPLE}"
    fi

    if [ $SW_AGENT_AUTHENTICATION ]; then
        SW_OPTS=$SW_OPTS "-DSW_AGENT_AUTHENTICATION=${SW_AGENT_AUTHENTICATION}"
    fi

    if [ $SW_AGENT_NAMESPACE ]; then
        SW_OPTS=$SW_OPTS "-DSW_AGENT_NAMESPACE=${SW_AGENT_NAMESPACE}"
    fi

    if [ $SW_AGENT_SPAN_LIMIT ]; then
        SW_OPTS=$SW_OPTS "-DSW_AGENT_SPAN_LIMIT=${SW_AGENT_SPAN_LIMIT}"
    fi

    if [ $SW_AGENT_IGNORE_SUFFIX ]; then
        SW_OPTS=$SW_OPTS "-DSW_AGENT_IGNORE_SUFFIX=${SW_AGENT_IGNORE_SUFFIX}"
    fi

    if [ $SW_AGENT_OPEN_DEBUG ]; then
        SW_OPTS=$SW_OPTS "-DSW_AGENT_OPEN_DEBUG=${SW_AGENT_OPEN_DEBUG}"
    fi

    if [ $SW_AGENT_OPERATION_NAME_THRESHOLD ]; then
        SW_OPTS=$SW_OPTS "-DSW_AGENT_OPERATION_NAME_THRESHOLD=${SW_AGENT_OPERATION_NAME_THRESHOLD}"
    fi

    SW_AGENT_COLLECTOR_BACKEND_SERVICES=${SW_AGENT_COLLECTOR_BACKEND_SERVICES:-"skywalking:11800"}
    SW_OPTS=$SW_OPTS "-DSW_AGENT_COLLECTOR_BACKEND_SERVICES=${SW_AGENT_COLLECTOR_BACKEND_SERVICES}"

    SW_LOGGING_FILE_NAME=${SW_LOGGING_FILE_NAME:-"skywalking-api.log"}
    SW_OPTS=$SW_OPTS "-DSW_LOGGING_FILE_NAME=${SW_LOGGING_LEVEL}"

    SW_LOGGING_LEVEL=${SW_LOGGING_LEVEL:-"DEBUG"}
    SW_OPTS=$SW_OPTS "-DSW_LOGGING_LEVEL=${SW_LOGGING_LEVEL}"

    if [ $SW_LOGGING_DIR ]; then
        SW_OPTS=$SW_OPTS "-DSW_LOGGING_DIR=${SW_LOGGING_DIR}"
    fi

    if [ $SW_LOGGING_MAX_FILE_SIZE ]; then
        SW_OPTS=$SW_OPTS "-DSW_LOGGING_MAX_FILE_SIZE=${SW_LOGGING_MAX_FILE_SIZE}"
    fi

    if [ $SW_LOGGING_MAX_HISTORY_FILES ]; then
        SW_OPTS=$SW_OPTS "-DSW_LOGGING_MAX_HISTORY_FILES=${SW_LOGGING_MAX_HISTORY_FILES}"
    fi

    if [ $SW_MYSQL_TRACE_SQL_PARAMETERS ]; then
        SW_OPTS=$SW_OPTS "-DSW_MYSQL_TRACE_SQL_PARAMETERS=${SW_MYSQL_TRACE_SQL_PARAMETERS}"
    fi
fi
